module.exports = {
  address: require("./address.controller"),
  auth: require("./auth.controller"),
  catalog: require("./catalog.controller"),
  company: require("./company.controller"),
  customer: require("./customer.controller"),
  deposit: require("./deposit.controller"),
  file: require("./file.controller"),
  geofencing: require("./geofencing.controller"),
  lang: require("./lang.controller"),
  realtime: require("./realtime.controller"),
  status: require("#modules/status/status.controller.js"),
  types: require("./types.controller"),
  user: require("./user.controller"),
  invoice: require("./invoice.controller"),
  tag: require("./tag.controller"),
  //file: require("./upload.controller"),
  matrix: require("./matrix.controller"),
  tarif: require("./tarif.controller"),
  invoicePendingBilling: require("./invoicePendingBilling.controller"),
  engin: require("./engin.controller"),
  vehicule: require("./vehicule.controller"),
  inventory: require("./inventory.controller"),
  object: require("./object.controller"),
  validator:require("./validator.controller"),
  worksite:require("./worksite.controller"),
  communication:require("#modules/communication/communication.controller.js"),
  menu:require("./menu.controller"),
  xlocation: require('./xlocation.controller'),
  xnavixy: require('#modules/navixy/navixy.controller.js'),
  fileGenerator: require('./fileGenerator.controller'),
  logs: require('./logs.controller'),
  staff: require('./staff.controller'),
  device: require('./device.controller'),
  relation: require('./relation.controller'),
  order: require('./order.controller'),
  config: require('./config.controller'),
  provider: require('./provider.controller'),
  positions: require('./positions.controller'),
  xflespi: require('../../modules/flespi/flespi.controller'),
  fcmtoken: require('../../modules/fcmtoken/fcmtoken.controller'),
  statistics: require('./statistics.controller'),

};
